package de.hpi.data_change.imdb.parsing.plot;

public enum STATE {
    LOOKING_FOR_START, EXPECT_PLOT_START_LINE, PARSE_TITLE, PARSE_BEGIN_PLOTDESCR, PARSE_PLOTDESCR, LOOK_FOR_AUTHOR_BEGIN, LOOK_FOR_AUTHOR_OR_PLOTBEGIN, EXPECT_PLOT_START_LINE_OR_PLOT,
}
